### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by chtmorris** [davidoevans/react-redux-dapp#10]
<img width="1489" alt="screen shot 2017-04-15 at 2 35 20 pm" src="https://cloud.githubusercontent.com/assets/5326519/25066056/5c171092-21e9-11e7-8344-f72b6c7a4822.png">

I am using Node v7.3.0 and have the latest truffle and testrpc installed.  Any ideas?

**Comment by davidoevans** [comment]
Hi @chtmorris.

Did you run `truffle compile` from the project directory?  That's what generates the *.json artifacts in that directory.

Let me know if that works.

Thanks,

Dave./

**Comment by chtmorris** [comment]
Haha.  Yup.  Thanks Dave.  This is an awesome resource.

**Comment by davidoevans** [comment]
Glad it's helpful.  Thanks Charlie.
